---
- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev-environment.yml
    - vars/aws-creds.yml

  tasks:

  - name: Create required security groups
    ec2_group:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ item.rules }}"
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
    with_items: "{{security_groups}}"

  - name: Launch instances
    ec2_instance: 
      region: "{{ ec2_region }}"
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      key_name: "{{ item.keypair }}"
      security_groups: "{{ item.group }}"
      instance_type: "{{ item.instance_type }}"
      image_id: "{{ item.image }}"
      tags: "{{ item.instance_tags }}"
      exact_count: "{{ item.exact_count }}"
      wait: true
    register: ec2_instance
    with_items: "{{ec2_instances}}"
